[package]
name = "fuzzy_dbscan"
version = "0.2.0"
authors = ["Christoph Schulz <schulzcbs@gmail.com>"]
description = "An implementation of the FuzzyDBSCAN algorithm"
homepage = "https://github.com/schulzch/fuzzy_dbscan"
repository = "https://github.com/schulzch/fuzzy_dbscan"
readme = "README.md"
keywords = [
    "fuzzy",
    "cluster",
    "clustering",
    "FuzzyDBSCAN",
    "DBSCAN"
]
categories = ["algorithms"]
license = "Apache-2.0"

[dev-dependencies]
rand = "0.3"
svg = "0.5"
