[package]
name = "utils"
edition = "2018"
version = "0.0.0"
authors = ["Christoph Schulz <schulzcbs@gmail.com>"]
license = "Apache-2.0"
description = """
Common utilities for testing.
"""

[dependencies]
fuzzy_dbscan = { path = ".." }
rand = "0.5"
svg = "0.5"
